Slowers-Team/Slowers-App

README.md

**Changes:**
- copy-paste installation instructions from example app
- links to documentation / project management
- link to staging server
- small introduction

13 fixing readme

---

frontend/eslint.config.js
frontend/src/App.jsx
frontend/src/components/FlowerForm.jsx
frontend/src/components/FlowerList.jsx
frontend/src/services/flowers.js

**Changes:**
- `frontend/src/App.jsx` split into multiple files in the same way as in https://github.com/fullstack-hy2020/part2-notes-frontend/tree/part5-8
- `id` HTML attributes added to buttons and input fields

18 refactor frontend into smaller components

---

frontend/.gitignore
frontend/src/components/FlowerForm.jsx
frontend/src/components/RegisterForm.jsx

Added labels for inputs so that unit tests can find them with getByLabelText
closes #25

25 missing labels in forms

---

frontend/src/pages/HomePage.jsx

Fixed a bug where deleting a flower causes all flowers with the same name to disappear from view. The solution to this bug was found by @Halmela .
Closes #40

Fixing the bug found in issue #40

---

backend/go.mod
backend/go.sum
backend/main.go
backend/site.go
frontend/src/App.jsx
frontend/src/Misc.css
frontend/src/components/FlowerForm.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/SitePage.jsx
frontend/src/services/flowers.js

In the user story's acceptance criteria it says "Added flowers show up in the site flower list", but I think that's more part of the user story "Grower can view the list of flowers for each site", at least in my opinion. That's why I didn't add it here, even though it's listed in the acceptance criteria at the moment.

51 grower can add flowers to sites

---

backend/site.go

Fixed the bug found in issue #54 .

Fix the bug found in issue#54

---

backend/main.go

Fixed the bug found is issue #57

Update deleteFlower to also delete the flower from its sites list

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/components/FlowerForm.jsx
frontend/src/components/FlowerList.jsx
frontend/src/components/LogIn.jsx
frontend/src/components/NewSiteForm.jsx
frontend/src/components/RegisterForm.jsx
frontend/src/components/SiteFlexbox.jsx
frontend/src/components/grower/GrowerFlowerList.jsx
frontend/src/components/retailer/RetailerFlowerList.jsx
frontend/src/i18n.js
frontend/src/layouts/GrowerLayout.jsx
frontend/src/layouts/RetailerLayout.jsx
frontend/src/main.jsx
frontend/src/pages/GrowerFlowerPage.jsx
frontend/src/pages/GrowerHomePage.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/RegisterPage.jsx
frontend/src/pages/RetailerFlowerPage.jsx
frontend/src/pages/RetailerHomePage.jsx
frontend/src/pages/SitePage.jsx
frontend/src/pages/TermsPage.jsx
frontend/src/translations.json

**Changes:**
- Add `react-i18next` internationalization framework to `frontend/package.json`
- Set up `react-i18next` in `frontend/src/i18n.js`
- Add language selection links to the top right corner of each page
- Add English and Finnish translations to the file `frontend/src/translations.json` for each UI text

71 user can change the language support for internationalization

---

frontend/tests/components/LogIn.test.jsx
frontend/tests/components/RegisterForm.test.jsx
frontend/vite.config.js

**Changes:**
- Add `frontend/src/i18n.js` to `setupFiles` in `frontend/vite.config.js`
- Update login button text `Log In`->`Log in` in `frontend/tests/components/LogIn.test.jsx`
- Handle role selection and terms accepting in `frontend/tests/components/RegisterForm.test.jsx`

79 internationalization broke frontend unit tests

---

.gitignore
backend/application/application.go
backend/database/database.go
backend/database/user.go
backend/handlers/user.go
frontend/src/App.jsx
frontend/src/components/UserInfo.jsx
frontend/src/pages/UserPage.jsx
frontend/src/services/users.js
frontend/src/translations.json

User can see their profile information by clicking Profile-button in navigation bar. It displays current login information and has a button with which user can switch their role. Switching roles is immediately reflected on web page. Every element has a translation in English and Finnish.
New API routes:
- `GET /api/user` fetches currently logged in user's information without password
- input: -
- output: `{'_id: ID, username: string, email: string, password: "", role: string}` 
- `POST /api/user/role` switches currently logged in user's role to the one supplied
- input: string [new role]
- output: string [new role]

73 user can manage their role

---

backend/apitests/flowers_test.go
backend/apitests/sites_test.go
backend/apitests/users_test.go
backend/database/database.go
backend/database/flower.go
backend/database/site.go
backend/database/tests/flower_test.go
backend/handlers/flower.go
backend/handlers/handlers.go
backend/handlers/site.go
backend/handlers/user.go
backend/testdata/flower.go
backend/testdata/site.go
backend/testdata/user.go

This pull request adds two functions:
https://github.com/Slowers-Team/Slowers-App/blob/b837a237e9e05a2d9b406287853448f368786fd9/backend/database/database.go#L94-L103
which tries to parse an `ObjectID` from a `string`.
and
https://github.com/Slowers-Team/Slowers-App/blob/b837a237e9e05a2d9b406287853448f368786fd9/backend/handlers/handlers.go#L17-L32
which tries to fetch currently logged in user's ID from local context.
Rest of changes are converting the existing code to use these functions and making tests work.
I'd like to know, if the changes I made to tests are correct, because I am not confident in using testify.
Closes #86

83 backend function for fetching current user

---

backend/apitests/flowers_test.go
backend/apitests/sites_test.go
backend/apitests/users_test.go
backend/application/application.go
backend/database/tests/flower_test.go
backend/database/tests/site_test.go
backend/database/tests/user_test.go
backend/testdata/flower.go
backend/testdata/site.go
backend/testdata/user.go

**Unit tests for the following database functions in the backend:**
- backend/database/user.go
- GetUserByID()
- SetUserRole()
- backend/database/flower.go
- GetUserFlowers()
- GetAllFlowersRelatedToSite()
- backend/database/site.go
- GetSite()
- DeleteSite()
- AddFlowerToSite()
- GetSiteByID()
Closes #110

110 missing unit tests for database functions in backend

---

frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/NavigationBar.jsx
frontend/src/layouts/GrowerLayout.jsx
frontend/src/layouts/RetailerLayout.jsx
frontend/src/pages/SitePage.jsx

<h1>Main changes</h1>
Improved the look of the main navigation. Changed the navigation of both grower and retailer's page to work as tabs.
<h2>App.css</h2>
- Styling to make the offcanvas thinner. Actually just noticed this does not work after having moved the main navigation to components. Will be fixed.
<h2>NavigationBar.jsx</h2>
<h3>Navbar</h3>
- Added a button, which looks like a menu icon to open the offcanvas before the Navbar.Brand as the Navbar's own offcanvas would not allow "profile" and "language" to be left at "normal" navigation bar.
- Changed Navbar.Brand to work as a link to just "/", which currently links to /retailer or /grower based on default role (not sure if it should do this or just send to the homepage of the one open) and to /login.
- Removed Navbar collapsing as …

108 user can view updated navigation UI

---

frontend/src/components/FlowerList.jsx
frontend/src/components/FlowerModal.jsx
frontend/src/components/ModifyFlowerForm.jsx
frontend/src/components/SiteFlexbox.jsx
frontend/src/components/UserInfo.jsx
frontend/src/components/VisibilityButton.jsx
frontend/src/components/grower/AddFlower.jsx
frontend/src/components/grower/GrowerFlowerList.jsx
frontend/src/components/image/AddImage.jsx
frontend/src/components/image/ImageForm.jsx
frontend/src/components/retailer/RetailerFlowerList.jsx
frontend/src/layouts/Grower.css
frontend/src/pages/GrowerFlowerPage.jsx
frontend/src/pages/GrowerSitesPage.jsx
frontend/src/pages/SitePage.jsx
frontend/src/pages/TermsPage.jsx

1. Unify visually identical, but different id having buttons of flower-pages under same class.
If different behavior is necessary, it can be made with specifying both the id and className.
2. Add hovering and clicking effects to flower-buttons (darker and even darker)
3. Hide visibility-button from flowers that do not have a favorite image

173 button improvements

---

frontend/src/components/FlowerList.jsx
frontend/src/components/FlowerModal.jsx
frontend/src/components/ModifyFlowerForm.jsx
frontend/src/components/SiteFlexbox.jsx
frontend/src/components/UserInfo.jsx
frontend/src/components/VisibilityButton.jsx
frontend/src/components/grower/AddFlower.jsx
frontend/src/components/grower/GrowerFlowerList.jsx
frontend/src/components/image/AddImage.jsx
frontend/src/components/image/ImageForm.jsx
frontend/src/components/retailer/RetailerFlowerList.jsx
frontend/src/layouts/Grower.css
frontend/src/pages/GrowerFlowerPage.jsx
frontend/src/pages/GrowerSitesPage.jsx
frontend/src/pages/SitePage.jsx
frontend/src/pages/TermsPage.jsx

Reverts Slowers-Team/Slowers-App#174
This was done for accidentally done to main

Revert "173 button improvements"

---

frontend/src/components/FlowerInfoTab.jsx
frontend/src/components/FlowerList.jsx
frontend/src/components/FlowerModal.jsx
frontend/src/components/ModifyFlowerForm.jsx
frontend/src/components/SiteFlexbox.jsx
frontend/src/components/UserInfo.jsx
frontend/src/components/VisibilityButton.jsx
frontend/src/components/grower/AddFlower.jsx
frontend/src/components/grower/GrowerFlowerList.jsx
frontend/src/components/image/AddImage.jsx
frontend/src/components/image/ImageForm.jsx
frontend/src/components/retailer/RetailerFlowerList.jsx
frontend/src/layouts/Grower.css
frontend/src/pages/GrowerFlowerPage.jsx
frontend/src/pages/GrowerSitesPage.jsx
frontend/src/pages/SitePage.jsx
frontend/src/pages/TermsPage.jsx

Orignal PR: #174 
> Unify visually identical, but different id having buttons of flower-pages under same class.
> If different behavior is necessary, it can be made with specifying both the id and className.
> 
> Add hovering and clicking effects to flower-buttons (darker and even darker)
> 
> Hide visibility-button from flowers that do not have a favorite image
Original PR was accidentally merged to main. 
Closes #173

173 button improvements FINAL

---

backend/apitests/users_test.go
backend/handlers/user.go

222 add new business owner role options to backend and mongo database, part 2

---

.devcontainer/backend-container/devcontainer.json
.devcontainer/frontend-container/devcontainer.json
.gitignore
README.md
backend/.air.toml
backend/dev.Dockerfile
backend/docker-compose.dev.yml
dbs/.gitignore
dbs/docker-compose.dev.yml
dbs/mongo-init.js
dbs/psql-init.sql
docker-compose.dev.yml
frontend/dev.Dockerfile
frontend/docker-compose.dev.yml
frontend/vite.config.js
nginx.dev.conf

Developer containers for frontend, backend, databases and combination of all three. Includes live reload for backend development.

250 add developer containers

---

frontend/cypress/e2e/logged_in.cy.js
frontend/cypress/e2e/login.cy.js
frontend/src/App.jsx
frontend/src/pages/GrowerHomePage.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/marketplaceHomePage.jsx
frontend/src/translations.json

for the empty homepages, a descriptive title that tells the user which page they are

265 placeholder titles for empty pages

---

backend/database/psql/business.go
backend/database/psql/database.go
backend/database/psql/tests/business_test.go
backend/handlersPsql/business.go
backend/testdataPsql/business.go

Small pull request containing renaming of Business SQL fields and test for creating business.

326 create a query to find out if user is business owner andor part of a business

---

backend/database/psql/business.go
backend/database/psql/schema.sql
backend/handlersPsql/business.go
backend/testdataPsql/business.go
frontend/src/components/CreateBusinessForm.jsx
frontend/src/translations.json

339 add a field for business id on the form

---

backend/database/psql/business.go
backend/database/psql/schema.sql
backend/handlersPsql/business.go
frontend/src/components/CreateBusinessForm.jsx
frontend/src/pages/UserPage.jsx
frontend/src/services/business.js

- delivery option added to businesses table
- if grower, delivery is what the user picks
- if retailer, delivery is always 'no'

Delivery added on business table

---

backend/database/psql/business.go
backend/database/psql/schema.sql
backend/handlersPsql/business.go
frontend/src/components/BusinessInfo.jsx
frontend/src/components/CreateBusinessForm.jsx
frontend/src/pages/BusinessPage.jsx
frontend/src/translations.json

321 display business information on business page

---

backend/application/application.go
backend/handlersPsql/membership.go
frontend/src/services/business.js

367 make an add membership  function in business service in frontend

---

frontend/src/services/business.js

Added getAllMembers function to services/business.js

---

frontend/src/App.jsx
frontend/src/components/EmployeesList.jsx
frontend/src/layouts/BusinessLayout.jsx
frontend/src/pages/BusinessEmployeesPage.jsx
frontend/src/translations.json

Branch can be removed after merge.

Create employees tab to business pages, rename businesspage to business

---

frontend/src/components/NavigationBar.jsx
frontend/src/pages/BusinessPage.jsx
frontend/src/pages/UserPage.jsx

365 move business registration form to business page and show it if user has no business membership

---

frontend/src/App.jsx
frontend/src/components/NavigationBar.jsx

Branch can be removed after merge (again)

Fix link in navbar, remove routing to home if role is only "grower" or "retailer"

---

backend/handlersPsql/membership.go
frontend/src/components/AddEmployeeForm.jsx
frontend/src/components/NavigationBar.jsx
frontend/src/pages/BusinessEmployeesPage.jsx
frontend/src/translations.json

378 add a form to add an employee in the employee tab

---

backend/application/application.go
backend/database/psql/database.go
backend/handlersPsql/business.go
backend/handlersPsql/membership.go
backend/utils/utils.go
frontend/src/components/AddEmployeeForm.jsx
frontend/src/components/EmployeesList.jsx
frontend/src/components/NavigationBar.jsx
frontend/src/pages/BusinessEmployeesPage.jsx
frontend/src/services/business.js
frontend/src/utils.js

376 make a list that contains all business members in employee tab

---

backend/application/application.go
backend/databases/sql/database.go
backend/databases/sql/membership.go
backend/handlers/membership.go

391 new add routing handler and db handler in backend for editing a membership

---

backend/handlers/tests/user_test.go
backend/handlers/user.go
backend/utils/tests/utils_test.go

400 add relevant unittests

---

frontend/src/App.jsx
frontend/src/Authenticator.jsx
frontend/src/layouts/BusinessLayout.jsx
frontend/src/pages/GrowerHomePage.jsx
frontend/src/pages/RetailerHomePage.jsx
frontend/src/translations.json

Also updated some translations.
Branch can be removed after merge.

405 Add "Retailer" tab to business page

---

backend/databases/sql/business.go
backend/databases/sql/membership.go
backend/handlers/business.go
backend/handlers/handlers.go
backend/main.go

Added more comments to the code
Do not delete branch in case more comments need to be added

415 go docs for most used and least infomative handlers
